blank_issues_enabled: false
contact_links:
  - name: Community Forum - SonarLint for Visual Studio
    url: https://community.sonarsource.com/c/sl/visual-studio/35
    about: Request support or report a bug.
  - name: Community Forum - Report False-positive / False-negative
    url: https://community.sonarsource.com/c/clean-code/fp/7
    about: Report problems with raised issues.
  - name: Community Forum - Product Manager for a Day
    url: https://community.sonarsource.com/c/sl/pm-for-a-day-sl/41
    about: Suggest new feature.
