name: Create Milestone

on:
  milestone:
    types: ["created"]

jobs:
  Log_job:
    name: Log payload from created milestone
    runs-on: ubuntu-latest
    steps:
      - uses: pavel-mikula-sonarsource/GitHubActionPlayground/Logging@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
