# This is a basic workflow to help you get started with Actions

name: KanbanStartProgress

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  project_card:
    types: ["moved"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  # This workflow contains a single job called "assign_self"
#  assign_self:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/pavel-mikula-sonarsource/GitHubActionPlayground/v0.3'. Did you forget to run actions/checkout before running your local action?
    #Valid for local action of private repo
    - uses: actions/checkout@v2

    - name: Hello world action step
      id: hello
      uses: pavel-mikula-sonarsource/GitHubActionPlayground@v0.3
      with:
        who-to-greet: 'Lorem ipsum'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"