name: Issue Labeled

on:
  issues:
    types: ["labeled"]

jobs:
  CreateCardForIssueFromLabel_DefaultType_job:
    name: Create card from label
    runs-on: ubuntu-latest
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # Only limited global functions are available in this context https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions
    if: |
        github.event.issue.state == 'Open'
        && startsWith(github.event.label.name, 'Type:')

    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateCardForIssueFromLabel@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          project-id: 12681611        # Backlog project ID

  CreateCardForIssueFromLabel_NondefaultKind_job:
    name: Create card from label
    runs-on: ubuntu-latest
    if: |
        github.event.issue.state == 'Open'
        && startsWith(github.event.label.name, 'Kind:')

    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateCardForIssueFromLabel@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          project-id: 12681611      # Backlog project ID
          label-prefix: "Kind:"     # Optional. Update startsWith condition above if you change it.

  CreateCardForLabeledIssue_job:
    name: Create card for labeled issue
    runs-on: ubuntu-latest
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # Only limited global functions are available in this context https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions
    if: |
        github.event.issue.state != 'closed'
        && startsWith(github.event.label.name, 'Sprint:')

    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateCardForIssue@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 11144556     # Kanban "To do" column

  LogPayload_job:
    name: Log payload
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/LogPayload@v1
