name: Log Milesoned Issue

on:
  issues:
    types: ["milestoned"]

jobs:
  log:
    name: Log
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(`Payload: ${JSON.stringify(context.payload, undefined, 2)}`);
