name: Milesone Issue

on:
  issues:
    types: ["milestoned"]

jobs:
  create_card:
    name: Create card
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const TODO_COLUMN = 11144556;
            console.log("Creating Issue card");
            github.projects.createCard({ column_id: TODO_COLUMN, content_id: issue.id, content_type: "Issue" });
            console.log("Done");
