name: Request review

on:
  pull_request:
    types: ["review_requested"]

jobs:
    say_hello:
        runs-on: ubuntu-latest

        steps:
            # https://github.com/actions/github-script
            - uses: actions/github-script@v3
                with:
                    github-token: ${{secrets.GITHUB_TOKEN}}
                    script: |
                        // var issue = await github.request(context.payload.project_card.content_url);
                        // console.log(`issue ${issue}`);
                        // console.log(`issue ${JSON.stringify(issue, undefined, 2)}}`);
                        // console.log(`issue.data.number ${issue.data.number}`);
                        // if(!issue.data.assignee){
                        //     github.issues.addAssignees({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issue.data.number, assignees: [context.payload.sender.login] });
                        // }
                        console.log(`The event payload: ${JSON.stringify(context.payload, undefined, 2)}`);

#https://api.github.com/repos/pavel-mikula-sonarsource/GitHubActionPlayground/issues/1

#jobs:
#    assign_to_self:
#        runs-on: ubuntu-latest
#        if: |
#            github.event.changes.column_id.from == 11144556
#            && github.event.project_card.column_id == 11144557
#            && github.event.project_card.content_url != null
#        steps:
#          # https://github.com/actions/github-script
#          - uses: actions/github-script@v3
#            with:
#                github-token: ${{secrets.GITHUB_TOKEN}}
#                script: |
#                    var issue = await github.request(context.payload.project_card.content_url);
#                    console.log(`issue ${issue}`);
#                    console.log(`issue ${JSON.stringify(issue, undefined, 2)}}`);
#                    console.log(`issue.data.number ${issue.data.number}`);
#                    if(!issue.data.assignee){
#                        github.issues.addAssignees({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issue.data.number, assignees: [context.payload.sender.login] });
#                    }
#                    console.log(`The event payload: ${JSON.stringify(context.payload, undefined, 2)}`);


