name: Request review

on:
  pull_request:
    types: ["review_requested"]

jobs:
  RequestReview_job:
    name: Request review
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/RequestReview@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 11144558     # Kanban "Review in progress" column

  LogPayload_job:
    name: Log payload
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/LogPayload@v1