name: Assign card to sender

on:
  project_card:
    types: ["moved"]

jobs:
  AssginCardToSender_job:
    runs-on: ubuntu-latest
    if: |
        github.event.changes.column_id.from === 11144556
        && github.event.project_card.content_url !== null
    steps:
      - uses: sonarsource/gh-action-lt-backlog/AssignCardToSender@Pavel/AssignCardToSender
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
