name: Start Progress

on:
  project_card:
    types: ["moved"]

jobs:
  assign_to_self:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(`Payload: ${JSON.stringify(context.payload, undefined, 2)}`);


