name: Submit Review

on:
  pull_request_review:
    types: ["submitted"]

jobs:
  assign_and_move_card:
    name: Assign issue to PR author and move Kanban card
    runs-on: ubuntu-latest
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # PRs from forks don't have required token authorization
    if: |
        github.event.pull_request.head.repo.full_name == github.repository
        && (github.event.review.state == 'approved' || github.event.review.state == 'changes_requested')

    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const TODO_COLUMN = 11144556;
            const IN_PROGRESS_COLUMN = 11144557;
            const REVIEW_IN_PROGRESS_COLUMN = 11144558;
            const REVIEW_APPROVED_COLUMN = 11144559;
            const DONE_COLUMN = 11144560;
            //
            async function getIssue(issue_number) {
                try {
                    return (await github.issues.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number
                    })).data;
                }
                catch (error) {
                    console.log(`Issue #${issue_number} not found: ${error}`);
                    return null;
                }
            }
            //
            async function findCard(content_url) {
                // Columns are searched from the most probable one
                const allColumns = [REVIEW_IN_PROGRESS_COLUMN, REVIEW_APPROVED_COLUMN, IN_PROGRESS_COLUMN, TODO_COLUMN, VALIDATE_PEACH_COLUMN, DONE_COLUMN];
                for (let i = 0; i < allColumns.length; i++) {
                    let cards = await github.projects.listCards({ column_id: allColumns[i] });
                    let card = cards.data.find(x => x.content_url == content_url);
                    if (card) {
                        return card;
                    }
                }
                console.log("Card not found for: " + content_url);
                return null;
            }
            //
            async function anyRequestedReviewerRequestChanges() {
                const per_page = 100;   // Allowed maximum
                const latest = {};
                const pr = context.payload.pull_request;
                let reviews = null, page = 0;
                do {
                    page++;
                    reviews = (await github.pulls.listReviews({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.number,
                        per_page,
                        page
                    })).data;
                    for (let i = 0; i < reviews.length; i++) {
                        latest[reviews[i].user.login] = reviews[i];
                    }
                } while (reviews.length == per_page);
                for (let i = 0; i < pr.requested_reviewers.length; i++) {
                    const review = latest[pr.requested_reviewers[i]];
                    if (review != null && review.state == "CHANGES_REQUESTED") {
                        return true;
                    }
                }
                return false;
            }
            //
            async function removeAssignees(issue){
                const oldAssignees = issue.assignees.map(x => x.login);
                if (oldAssignees.length !== 0) {
                    console.log("Removing assignees: " + oldAssignees.join(", "));
                    await github.issues.removeAssignees({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issue.number,
                        assignees: oldAssignees
                    });
                }
            }
            //
            async function addAssignee(issue, login) {
                console.log("Assigning to: " + login);
                await github.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    assignees: [login]
                });
            }
            //
            async function processIssue(issue, anyRequestChanges) {
                if (issue.state == "open") {
                    await removeAssignees(issue);
                    addAssignee(issue, context.payload.pull_request.user.login);
                    const card = await findCard(issue.url);
                    // Approved & Commented should also go to "In progress" if somebody registers the YML for "commented"
                    const newColumn = context.payload.review.state == "approved" && !anyRequestChanges ? REVIEW_APPROVED_COLUMN : IN_PROGRESS_COLUMN;
                    if (card && card.column_id != newColumn) {
                        console.log("Moving card");
                        github.projects.moveCard({ card_id: card.id, position: "bottom", column_id: newColumn });
                    }
                }
            }
            //
            let processPR = true;
            const pr = context.payload.pull_request;
            const anyRequestChanges = anyRequestedReviewerRequestChanges(pr.number);
            const matches = pr.body.match(/Fixes\s*#\d+/gi);
            if (matches) {
                for (let i = 0; i < matches.length; i++) {
                    console.log("Processing linked issue: " + matches[i]);
                    let linkedIssue = await getIssue(matches[i].split("#")[1]);
                    if (linkedIssue) {
                        processPR = false;
                        processIssue(linkedIssue, anyRequestChanges);
                    }
                }
            }
            if (processPR) {
                console.log("Processing PR: #" + pr.number);
                const issue = await getIssue(pr.number);
                if (issue) {
                    processIssue(issue, anyRequestChanges);
                }
            }
            console.log("Done");
