name: Submit Review

on:
  pull_request_review:
    types: ["submitted"]

#        github.event.review.state == "changes_requested" // error
#        && github.event.review.state == "changes_requested"

jobs:
  assign_and_move_card:
    name: Assign issue to PR author and move Kanban card
    runs-on: ubuntu-latest
    if: |
        github.event != null // error
        && github.event != null

    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("Triggered: " + context.payload.review.state);
